#!/bin/bash -e

clone_url="$1"
if test -z "$clone_url"; then
  echo "usage: $0 https://github.com/owner/repo"
  exit 1
fi

export TMPDIR="$(pwd)/tmp"
mkdir -p $TMPDIR
clone_location=$(mktemp -d $TMPDIR/jekyll-acceptance.XXXXXX)
build_location=$(mktemp -d $TMPDIR/jekyll-acceptance.XXXXXX)

cleanup() { rm -rf "$clone_location" "$build_location"; }
if [ "$(uname -s)" = "Darwin" ]; then
  trap cleanup EXIT
fi

echo " ==> Cloning $clone_url into $clone_location"
git clone --recurse-submodules -q "$clone_url" "$clone_location"
echo " ==> Building it..."
BUNDLE_GEMFILE=$(pwd)/Gemfile bundle exec jekyll build -s "$clone_location" -d "$build_location"
