#!/bin/bash -xe

# Tiny site to get the ball rolling.
script/build-repo https://github.com/parkr/stuff

# Ben's site is great at catching weird bugs.
script/build-repo https://github.com/benbalter/benbalter.github.com

# 18F has been a huge user & supporter of Jekyll.
script/build-repo https://github.com/18F/federalist-docs

# Add this site because the author said it takes 15 minutes to build.
script/build-repo https://github.com/grantmakers/grantmakers.github.io
